name: End of Life Dependency Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read

jobs:
  eol-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run eol-check
        uses: xeol-io/xeol-action@v1.1.1
        with:
          path: "."